### ISSUE TITLE
Check-ex-spec exposes solution predicates

### ISSUE THREAD

**Issue by tdelv** [tnelson/Forge#63]
Check-ex-spec downloads compiled versions of the wheats and chaffs so that students are unable to read the solution code. However, if a forge/core file imports a wheat (in #lang forge/core), it can print the predicate, thus exposing the solution code. There needs to be some way of hiding the contents of a predicate from this kind of interaction (ideally so that we can make it only usable via check-ex-spec).

Example exploit:
1) Create and run file with contents: 
```
#lang forge/check-ex-spec "forge2/undirected_tree"
```

2) In same directory, create and run file with contents:
```
#lang forge/core

(require "wheat_undirected_tree.rkt")

isUndirectedTree
```

**Comment by bennn** [comment]
Is `check-ex-spec` really the only thing that needs to use the predicate?

If so, then `wheat_undirected_tree.rkt` could provide an opaque struct instead of a predicate. And `check-ex-spec` could unwrap the struct.

Students would be able to unwrap the struct too, though, if they dig through the Forge code. So maybe it's not worth worrying about this.

Another idea is to delete the download files after every run ... but that's not perfect either.

**Comment by tdelv** [comment]
Check-ex-spec is the only thing that should be requiring any of those downloaded files, yes.

We aren't going to try to defend against overly malicious students; if they try to go into the depths of Forge to find a way to expose the solution, we will have very strong evidence of attempting to cheat. We just want basic level of security.

We want to keep a local version so that they can work offline.

**Comment by bennn** [comment]
Discussed with Tim & Thomas today.

Students aren't using `forge/core` (yet) and aren't requiring forge models, so this is lower priority.
